version: '3.8'
services:
        php-apache:
                container_name: web-server
                build:
                        context: ./crud-ci3
                        dockerfile: Dockerfile
                depends_on:
                        - db
                volumes:
                        - ./crud-ci3:/var/www/html
                ports:
                        - 8080:80

         db:
                 container_name: database
                 image: mysql
                 restart: always
                 environment:
                         MYSQL_ROOT_PASSWORD: root
                         MYSQL_DATABASE: crud-ci3.sql
                         MYSQL_USER: root
                         MYSQL_PASSWORD: root
                  ports:
                          - 3306:3306

          phpmyadmin:
                  container_name: database-management
                  image: phpmyadmin
                  restart: always
                  environment:
                          PMA_HOST: db
                  depends_on:
                          - db
                  ports:
                          - 8081:80

